# Generated by Django 5.0.2 on 2024-02-08 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_caretaker'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.CharField(default='P1', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('property_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('property_images', models.FileField(blank=True, null=True, upload_to='property_images/')),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
