# Generated by Django 5.0.2 on 2024-04-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='property/static/images/profile_pic'),
        ),
    ]
