# Generated by Django 5.0.2 on 2024-03-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_alter_tenant_tenant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='unit_id',
            field=models.CharField(editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
