# Generated by Django 5.0.2 on 2024-04-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_alter_tenant_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='profile_pic',
            field=models.FileField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
