# Generated by Django 5.0.2 on 2024-02-08 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_id', models.CharField(default='CO1', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract_image', models.FileField(blank=True, null=True, upload_to='contract_images/')),
                ('tenant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.tenant')),
                ('unit_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.unit')),
            ],
        ),
    ]
