# Generated by Django 5.0.2 on 2024-04-03 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_alter_tenant_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='tenant_profile_pics/'),
        ),
    ]
