# Generated by Django 5.0.2 on 2024-04-17 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0006_alter_tenant_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='last_login',
        ),
    ]
