# Generated by Django 5.0.2 on 2024-03-26 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_monthlypayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyPayment',
        ),
    ]
