# Generated by Django 5.0.2 on 2024-04-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('property', '0008_rename_customuser_loginuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LoginUser',
            new_name='CustomUser',
        ),
    ]
